import CloseIcon from "./closeIcon";
import RefreshIcon from "./refreshIcon";
import SearchIcon from "./searchIcon";
import InfoIcon from "./infoIcon";
import ExpandIcon from "./expandIcon";
import BotIcon from "./botIcon";
import CandidateIcon from "./candidateIcon";
import GlobeIcon from "./globeIcon";
import RecentSearchIcon from "./recentSearchIcon";
import NoResultFoundIcon from "./noResultFoundIcon";
import EditIcon from "./editIcon";
import DeleteIcon from "./deleteIcon";
import SettingsIcon from "./settingsIcon";
import TestAnswerIcon from "./testAnswerIcon";
import BulkDownloadIcon from "./bulkDownloadIcon";
import TickIcon from "./TickIcon";
import UploadIcon from "./UploadIcon";
import DownArrow from "./DownArrow";
import InfoYellowIcon from "./infoYellowIcon";
import ExternalUrlIcon from "./externalUrlIcon";
import ErrorIcon from "./errorIcon";
import InfoIconShaded from "./infoIconShaded";
import SuccessIcon from "./successIcon";
import WarnIcon from "./warnIcon";
import QuestionMarkInfoIcon from "./questionMarkInfo";
import TickIconWithCircle from "./tickIconWithCircle";
import BackIcon from "./backIcon";
import InfoBlueIcon from "./infoBlueIcon";
import MessageIcon from "./MessageIcon";
import VerticalTimelineIcon from "./VerticalTimelineIcon";
import FlatSmileyIcon from "./FlatSmileyIcon";
import HappySmileyIcon from "./HappySmileyIcon";
import SadSmileyIcon from "./SadSmileyIcon";
import FeedbackIcon from "./FeedbackIcon";
import ThreeDotsIcon from "./ThreeDotsIcon";
import BellIcon from "./bellIcon";
import CandidateCircleIcon from "./candidateCircleIcon";
import BotCircleIcon from "./botCircleIcon";
import CollapseUpArrow from "./collapseUpArrow";
import CollapseDownArrow from "./collapseDownArrow";
import GoogleLogoIcon from "./googleLogoIcon";
import MailIcon from "./mailIcon";
import LockIcon from "./lockIcon";
import UndoIcon from "./undoIcon";
import SendIcon from "./sendIcon";
import EllipsisVertical from "./ellipsisVertical";
import WorkbenchIcon from "./workbenchIcon";
import StatsIcon from "./statsIcon";
import LeftArrowCircleIcon from "./leftArrowCircleIcon";
import SettingWithCircleIcon from "./settingWithCircleIcon";
import EditPencilIcon from "./editPencilIcon";
import AddContactIcon from "./addContactIcon";
import ResumeIcon from "./resumeIcon";
import DropBoxIcon from "./dropBoxIcon";
import UpArrowCircle from "./upArrowCircle";
import DownArrowCircle from "./downArrowCircle";
import LabelIcon from "./labels";
import ChangeStatusIcon from "./changeStatus";
import AwaitingApprovalIcon from "./awaitingApprovalIcon";
import UnderReviewIcon from "./underReview";
import ConversationFinishedIcon from "./conversationFinishedIcon";
import CandidatesShortlistedIcon from "./candidatesShortlistedIcon";
import ChangeStatusWhiteIcon from "./changeStatusWhiteIcon";
import LabelsWhiteIcon from "./labelsWhite";
import PublishIcon from "./publishIcon";
import PublishWhiteIcon from "./publishWhiteIcon";
import ChatbotIcon from "./chatbotIcon";
import ChatuserIcon from "./chatuserIcon";
import HamburgerMenuIcon from "./hamburgerMenuIcon";
import SupportIcon from "./supportIcon";
import FontSizeIcon from "./fontSizeIcon";
import RatingIcon from "./ratingIcon";
import RoundedLockIcon from "./roundedLockIcon";
import MailSupportIcon from "./mailSupportIcon";
import PrivacyIcon from "./privacyIcon";
import ApplicationStatusIcon from "./applicationStatusIcon";
import CandidateHomeIcon from "./candidateHomeIcon";
import CandidateWithdrawIcon from "./candidateWithdrawIcon";
import LogoutIcon from "./logoutIcon";
import UserYellowIcon from "./userYellowIcon";
import BlockIcon from "./blockIcon";
import AddIcon from "./addIcon";
import ExpandSectionIcon from "./expandSectionIcon";
import CollapseSectionIcon from "./collapseSectionIcon";
import BrowserIcon from "./browserIcon";
import YoutubePlayIcon from "./youtubePlayIcon";
import ImportFromOtherBotIcon from "./importFromOtherBotIcon";
import ImportContactIcon from "./importContactIcon";
import CloseIconOutlined from "./closeIconOutlined";
import ArrowDown from "./arrowDown";
import AddSectionIcon from "./addSectionIcon";
import ReportIcon from "./reportIcon";
import TranscriptIcon from "./transciptIcon";
import MoreActionIcon from "./moreActionIcon";
import CandidateResumeIcon from "./candidateResumeIcon";
import RecalculateIcon from "./recalculateIcon";
import WithdrawIcon from "./withdrawIcon";
import RemindIcon from "./remindIcon";
import ForwardCandidateIcon from "./forwardCandidateIcon";
import ForwardArrowIcon from "./forwardArrowIcon";
import UniversalSearchIcon from "./universalSearchIcon";
import EmptySearchListIcon from "./emptySearchListIcon";
import IconWhiteTick from "./iconWhiteTick";
import IconGreenTick from "./iconGreenTick";
import IconWarning from "./iconWarning";
import ConversationSnapshotBotIcon from "./conversationSnapshotBotIcon";
import ConversationSnapshotCandidateIcon from "./conversationSnapshotCandidateIcon";
import PlusIcon from "./plusIcon";
import BlackDeleteIcon from "./blackDeleteIcon";
import CalendarIcon from "./calendarIcon";
import YellowCalendarIcon from "./yellowCalendarIcon";
import ShakeBellIcon from "./shakeBellIcon";
import RoundedDownArrow from "./roundedDownArrow";
import ThumbsDownIcon from "./thumbsDownIcon";
import ThumbsUpIcon from "./thumbsUpIcon";
import TextEllipsis from "./textEllipsis";
import adhocWorflow from "./adhocWorflow";
import AddFaqQuestionIcon from "./addFaqQuestionIcon";
import FaqRedesignCreateModuleSvg from "./faqRedesignCreateModuleSvg";
import WidgetCalendarIcon from "./widgetCalendarIcon";
import CalendarSuccessIcon from "./calendarSuccessIcon";
import CalendarAwaitingIcon from "./calendarAwaitingIcon";
import CalendarReschedulingIcon from "./calendarReschedulingIcon";
import CalendarAwaitingConfirmationIcon from "./calendarAwaitingConfirmationIcon";
import CalendarFailedIcon from "./calendarFailedIcon";
import ImpressIcon from "./impressIcon";
import EvieIcon from "./evieIcon";
import WidgetexpandIcon from "./WidgetexpandIcon";
import RightArrow from "./rightArrow";
import ProctoringEnabledIcon from "./proctoringEnabledIcon";
import RecordingIcon from "./recordingIcon";
import ActiveGreenIcon from "./activeGreenIcon";
import RedCloseIcon from "./redCloseIcon";
import ProctoringErrorIcon from "./proctoringErrorIcon";
import NotesIcon from "./notesIcon";
import OrIcon from "./orIcon";
import TickIconGreenBg from "./tickIconGreenBg";
import LocationIcon from "./locationIcon";
import FunnelIcon from "./funnelIcon";
import WhiteTickGreenBg from "./whiteTickGreenBg";
import SideAnalytics from "./SideAnalytics";
import SideManageworkflows from "./SideManageworkflows";
import SideHome from "./SideHome";
import SideCandidates from "./SideCandidates";
import SideCandidatequeries from "./SideCandidatequeries";
import SideAudittrails from "./SideAudittrails";
import SideSettings from "./SideSettings";
import SideEmail from "./SideEmail";
import SideFaq from "./SideFaq";
import SideInsights from "./SideInsights";
import SideContentCatalogue from "./SideContentCatalogue";
import SideManageTeam from "./SideManageTeam";
import ImpressLogo from "./ImpressLogo";
import PictureIcon from "./pictureIcon";
import AttachmentIcon from "./attachmentIcon";
import DownloadIcon from "./downloadIcon";
import SmsIcon from "./smsIcon";
import WhatsAppIcon from "./whatsappIcon";
import FileDownloadIcon from "./fileDownloadIcon";
import RedCross from "./redCross";
import ProfileIcon from "./profileIcon";

import ViewIcon from "./ViewIcon";
import WorkflowLogsIcon from "./WorkflowLogsIcon";
import CandidateLogsIcon from "./CandidateLogsIcon";
import CopyIcon from "./CopyIcon";
import SadSmiley from "./sadSmiley";
import ThumbsDown from "./thumbsDown";
import decisionModalDeleteIcon from "./decisionModalDeleteIcon";
import decisionModalInfoIcon from "./decisionModalInfoIcon";
import decisionModalSingleIcon from "./decisionModalSingleIcon";
import bulbIcon from "./bulbIcon";
import DeleteBinIcon from "./deleteBinIcon";
import MobileMenu from "./mobileMenu";
import ClientIconAon from "./clientIconAon";
import userManualIcon from "./userManualIcon";
import ChatWithCustomerSupportIcon from "./ChatWithSupportIcon";
import EnquireConcernsIcon from "./EnquireConcernsIcon";
import EnquiryStatusIcon from "./EnquiryStatusIcon";
import BlogsIcon from "./BlogsIcon";
import CreateBotIcon from "./CreateBotIcon";
import dashboardIcon from "./dashboardIcon";
import EvaluationsIcon from "./EvaluationsIcon";
import settingsOrangeIcon from "./settingsOrangeIcon";
import ArrowRightIcon from "./ArrowRightIcon";
import QuestionIcon from "./questionIcon";
import AnswerIcon from "./answerIcon";
import highFiveIcon from "./highFiveIcon";
import DisableUserIcon from "./disableUserIcon";
import EnableUserIcon from "./enableUserIcon";
import RemoveUserIcon from "./removeUserIcon";
import SadSmileyDisabled from "./sadSmileyDisabled";
import FlatSmileyDisabled from "./flatSmileyDisabled";
import EmptyQuestionAndAnswersIcon from "./emptyQuestionAndAnswersIcon";
import TwoWayChatIcon from "./twoWayChatIcon";
import LockUserIcon from "./lockUserIcon";
import ReviewApplicantsIcon from "./reviewApplicantsIcon";
import ShortlistRejectIcon from "./shortListRejectIcon";
import AddUserIcon from "./addUserIcon";
import AuditTrailIcon from "./auditTrailIcon";
import InProgressIcon from "./inProgressIcon";
import UnderlineUploadIcon from "./underlineUploadIcon";
import GreyInfoIcon from "./greyInfoIcon";
import DeleteBinIconDashed from "./deleteBinIconDashed";
import CommentIcon from "./commentIcon";
import RejectIcon from "./rejectIcon";
import AdvanceNextIcon from "./advanceNext";
import MarkRemindedIcon from "./markAsReminded";
import RedoSectionIcon from "./redoSection";
import NotifyIcon from "./notifyIcon";
import ReconsiderIcon from "./reconsiderIcon";
import ReinstateIcon from "./reinstateIcon";
import EvaluateAnswerIcon from "./evaluateAnswerIcon";
import KeptInViewIcon from "./keptInViewIcon";
import ShortlistIcon from "./shortlistIcon";
import CollapseArrowRight from "./collapseArrowRight";
import CollapseArrowDown from "./collapseArrowDown";
import EhrSyncIcon from "./EhrSyncIcon";
import ExemptionRequestIcon from "./ExemptionRequestIcon";
import ExemptionRevokeIcon from "./ExemptionRevokeIcon";

function CallImIcons() {}

// define your new icons
CallImIcons.closeIcon = CloseIcon;
CallImIcons.searchIcon = SearchIcon;
CallImIcons.refreshIcon = RefreshIcon;
CallImIcons.infoIcon = InfoIcon;
CallImIcons.expandIcon = ExpandIcon;
CallImIcons.botIcon = BotIcon;
CallImIcons.candidateIcon = CandidateIcon;
CallImIcons.globeIcon = GlobeIcon;
CallImIcons.recentSearchIcon = RecentSearchIcon;
CallImIcons.noResultFoundIcon = NoResultFoundIcon;

CallImIcons.editIcon = EditIcon;
CallImIcons.deleteIcon = DeleteIcon;
CallImIcons.settingsIcon = SettingsIcon;
CallImIcons.testAnswerIcon = TestAnswerIcon;
CallImIcons.bulkDownloadIcon = BulkDownloadIcon;
CallImIcons.tickIcon = TickIcon;
CallImIcons.uploadIcon = UploadIcon;
CallImIcons.downIcon = DownArrow;
CallImIcons.collapseUpArrow = CollapseUpArrow;
CallImIcons.collapseDownArrow = CollapseDownArrow;
CallImIcons.infoYellowIcon = InfoYellowIcon;
CallImIcons.externalUrlIcon = ExternalUrlIcon;
CallImIcons.errorIcon = ErrorIcon;
CallImIcons.successIcon = SuccessIcon;
CallImIcons.warnIcon = WarnIcon;
CallImIcons.infoIconShaded = InfoIconShaded;
CallImIcons.questionMarkInfo = QuestionMarkInfoIcon;
CallImIcons.tickIconWithCircle = TickIconWithCircle;
CallImIcons.backIcon = BackIcon;
CallImIcons.infoBlueIcon = InfoBlueIcon;
CallImIcons.messageIcon = MessageIcon;
CallImIcons.verticalTimelineIcon = VerticalTimelineIcon;
CallImIcons.flatSmileyFaceIcon = FlatSmileyIcon;
CallImIcons.sadSmileyFaceIcon = SadSmileyIcon;
CallImIcons.happySmileyFaceIcon = HappySmileyIcon;
CallImIcons.feedbackIcon = FeedbackIcon;
CallImIcons.threeDotsIcon = ThreeDotsIcon;
CallImIcons.bellIcon = BellIcon;
CallImIcons.candidateCircleIcon = CandidateCircleIcon;
CallImIcons.botCircleIcon = BotCircleIcon;
CallImIcons.googleLogoIcon = GoogleLogoIcon;
CallImIcons.mailIcon = MailIcon;
CallImIcons.lockIcon = LockIcon;
CallImIcons.undoIcon = UndoIcon;
CallImIcons.sendIcon = SendIcon;
CallImIcons.ellipsisVertical = EllipsisVertical;
CallImIcons.workbenchIcon = WorkbenchIcon;
CallImIcons.statsIcon = StatsIcon;
CallImIcons.leftArrowCircleIcon = LeftArrowCircleIcon;
CallImIcons.settingWithCircleIcon = SettingWithCircleIcon;
CallImIcons.editPencilIcon = EditPencilIcon;
CallImIcons.addContactIcon = AddContactIcon;
CallImIcons.resumeIcon = ResumeIcon;
CallImIcons.dropBoxIcon = DropBoxIcon;
CallImIcons.upArrowCircle = UpArrowCircle;
CallImIcons.downArrowCircle = DownArrowCircle;

CallImIcons.labelIcon = LabelIcon;
CallImIcons.changeStatusIcon = ChangeStatusIcon;
CallImIcons.awaitingApprovalIcon = AwaitingApprovalIcon;
CallImIcons.underReviewIcon = UnderReviewIcon;
CallImIcons.conversationFinishedIcon = ConversationFinishedIcon;
CallImIcons.candidatesShortlistedIcon = CandidatesShortlistedIcon;
CallImIcons.changeStatusWhiteIcon = ChangeStatusWhiteIcon;
CallImIcons.labelsWhiteIcon = LabelsWhiteIcon;
CallImIcons.changeStatusWhiteIcon = ChangeStatusWhiteIcon;
CallImIcons.labelsWhiteIcon = LabelsWhiteIcon;
CallImIcons.publishIcon = PublishIcon;
CallImIcons.publishWhiteIcon = PublishWhiteIcon;
CallImIcons.chatbotIcon = ChatbotIcon;
CallImIcons.chatuserIcon = ChatuserIcon;
CallImIcons.hamburgerMenuIcon = HamburgerMenuIcon;
CallImIcons.supportIcon = SupportIcon;
CallImIcons.fontSizeIcon = FontSizeIcon;
CallImIcons.ratingIcon = RatingIcon;
CallImIcons.roundedLockIcon = RoundedLockIcon;
CallImIcons.mailSupportIcon = MailSupportIcon;
CallImIcons.privacyIcon = PrivacyIcon;
CallImIcons.applicationStatusIcon = ApplicationStatusIcon;
CallImIcons.candidateHomeIcon = CandidateHomeIcon;
CallImIcons.candidateWithdrawIcon = CandidateWithdrawIcon;
CallImIcons.logoutIcon = LogoutIcon;
CallImIcons.userYellowIcon = UserYellowIcon;
CallImIcons.blockIcon = BlockIcon;
CallImIcons.addIcon = AddIcon;
CallImIcons.expandSectionIcon = ExpandSectionIcon;
CallImIcons.collapseSectionIcon = CollapseSectionIcon;
CallImIcons.browserIcon = BrowserIcon;
CallImIcons.youtubePlayIcon = YoutubePlayIcon;
CallImIcons.importFromOtherBotIcon = ImportFromOtherBotIcon;
CallImIcons.importContactIcon = ImportContactIcon;
CallImIcons.closeIconOutlined = CloseIconOutlined;
CallImIcons.arrowDown = ArrowDown;
CallImIcons.addSectionIcon = AddSectionIcon;
CallImIcons.reportIcon = ReportIcon;
CallImIcons.transcriptIcon = TranscriptIcon;
CallImIcons.moreActionIcon = MoreActionIcon;
CallImIcons.candidateResumeIcon = CandidateResumeIcon;
CallImIcons.recalculateIcon = RecalculateIcon;
CallImIcons.withdrawIcon = WithdrawIcon;
CallImIcons.remindIcon = RemindIcon;
CallImIcons.forwardCandidateIcon = ForwardCandidateIcon;
CallImIcons.forwardArrowIcon = ForwardArrowIcon;
CallImIcons.universalSearchIcon = UniversalSearchIcon;
CallImIcons.emptySearchListIcon = EmptySearchListIcon;
CallImIcons.iconWhiteTick = IconWhiteTick;
CallImIcons.iconGreenTick = IconGreenTick;
CallImIcons.iconWarning = IconWarning;
CallImIcons.conversationSnapshotBotIcon = ConversationSnapshotBotIcon;
CallImIcons.conversationSnapshotCandidateIcon =
  ConversationSnapshotCandidateIcon;
CallImIcons.plusIcon = PlusIcon;
CallImIcons.blackDeleteIcon = BlackDeleteIcon;
CallImIcons.calendarIcon = CalendarIcon;
CallImIcons.yellowCalendarIcon = YellowCalendarIcon;
CallImIcons.shakeBellIcon = ShakeBellIcon;
CallImIcons.roundedDownArrow = RoundedDownArrow;
CallImIcons.thumbsDownIcon = ThumbsDownIcon;
CallImIcons.thumbsUpIcon = ThumbsUpIcon;
CallImIcons.textEllipsis = TextEllipsis;
CallImIcons.adhocWorflow = adhocWorflow;
CallImIcons.addFaqQuestionIcon = AddFaqQuestionIcon;
CallImIcons.faqRedesignCreateModuleSvg = FaqRedesignCreateModuleSvg;
CallImIcons.widgetCalendarIcon = WidgetCalendarIcon;
CallImIcons.calendarSuccessIcon = CalendarSuccessIcon;
CallImIcons.calendarAwaitingIcon = CalendarAwaitingIcon;
CallImIcons.calendarReschedulingIcon = CalendarReschedulingIcon;
CallImIcons.calendarAwaitingConfirmationIcon = CalendarAwaitingConfirmationIcon;
CallImIcons.calendarFailedIcon = CalendarFailedIcon;
CallImIcons.impressIcon = ImpressIcon;
CallImIcons.evieIcon = EvieIcon;
CallImIcons.WidgetexpandIcon = WidgetexpandIcon;
CallImIcons.rightArrow = RightArrow;
CallImIcons.proctoringEnabledIcon = ProctoringEnabledIcon;
CallImIcons.recordingIcon = RecordingIcon;
CallImIcons.activeGreenIcon = ActiveGreenIcon;
CallImIcons.redCloseIcon = RedCloseIcon;
CallImIcons.proctoringErrorIcon = ProctoringErrorIcon;
CallImIcons.NotesIcon = NotesIcon;
CallImIcons.orIcon = OrIcon;
CallImIcons.tickIconGreenBg = TickIconGreenBg;
CallImIcons.locationIcon = LocationIcon;
CallImIcons.funnelIcon = FunnelIcon;
CallImIcons.whiteTickWithGreenBg = WhiteTickGreenBg;
CallImIcons.SideAnalytics = SideAnalytics;
CallImIcons.SideManageworkflows = SideManageworkflows;
CallImIcons.SideHome = SideHome;
CallImIcons.SideCandidates = SideCandidates;
CallImIcons.SideCandidatequeries = SideCandidatequeries;
CallImIcons.SideAudittrails = SideAudittrails;
CallImIcons.SideSettings = SideSettings;
CallImIcons.SideEmail = SideEmail;
CallImIcons.SideFaq = SideFaq;
CallImIcons.SideInsights = SideInsights;
CallImIcons.SideContentCatalogue = SideContentCatalogue;
CallImIcons.SideManageTeam = SideManageTeam;
CallImIcons.ImpressLogo = ImpressLogo;
CallImIcons.pictureIcon = PictureIcon;
CallImIcons.attachmentIcon = AttachmentIcon;
CallImIcons.downloadIcon = DownloadIcon;
CallImIcons.smsIcon = SmsIcon;
CallImIcons.whatsappIcon = WhatsAppIcon;
CallImIcons.fileDownloadIcon = FileDownloadIcon;
CallImIcons.redCross = RedCross;
CallImIcons.ViewIcon = ViewIcon;
CallImIcons.WorkflowLogsIcon = WorkflowLogsIcon;
CallImIcons.CandidateLogsIcon = CandidateLogsIcon;
CallImIcons.CopyIcon = CopyIcon;
CallImIcons.sadSmiley = SadSmiley;
CallImIcons.thumbsDown = ThumbsDown;
CallImIcons.decisionModalDeleteIcon = decisionModalDeleteIcon;
CallImIcons.decisionModalInfoIcon = decisionModalInfoIcon;
CallImIcons.decisionModalSingleIcon = decisionModalSingleIcon;
CallImIcons.bulbIcon = bulbIcon;
CallImIcons.deleteBinIcon = DeleteBinIcon;
CallImIcons.mobileMenu = MobileMenu;
CallImIcons.clientIconAon = ClientIconAon;
CallImIcons.userManualIcon = userManualIcon;
CallImIcons.chatWithCustomerSupportIcon = ChatWithCustomerSupportIcon;
CallImIcons.enquireConcernsIcon = EnquireConcernsIcon;
CallImIcons.enquiryStatusIcon = EnquiryStatusIcon;
CallImIcons.blogsIcon = BlogsIcon;
CallImIcons.createBotIcon = CreateBotIcon;
CallImIcons.dashboardIcon = dashboardIcon;
CallImIcons.evaluationsIcon = EvaluationsIcon;
CallImIcons.arrowRightIcon = ArrowRightIcon;
CallImIcons.settingsOrangeIcon = settingsOrangeIcon;
CallImIcons.highFiveIcon = highFiveIcon;
CallImIcons.profileIcon = ProfileIcon;
CallImIcons.questionIcon = QuestionIcon;
CallImIcons.answerIcon = AnswerIcon;
CallImIcons.disableUserIcon = DisableUserIcon;
CallImIcons.enableUserIcon = EnableUserIcon;
CallImIcons.removeUserIcon = RemoveUserIcon;
CallImIcons.sadSmileyDisabled = SadSmileyDisabled;
CallImIcons.flatSmileyDisabled = FlatSmileyDisabled;
CallImIcons.emptyQuestionAndAnswersIcon = EmptyQuestionAndAnswersIcon;
CallImIcons.twoWayChatIcon = TwoWayChatIcon;
CallImIcons.lockUserIcon = LockUserIcon;
CallImIcons.reviewApplicantsIcon = ReviewApplicantsIcon;
CallImIcons.shortlistRejectIcon = ShortlistRejectIcon;
CallImIcons.addUserIcon = AddUserIcon;
CallImIcons.auditTrailIcon = AuditTrailIcon;
CallImIcons.inProgressIcon = InProgressIcon;
CallImIcons.underlineUploadIcon = UnderlineUploadIcon;
CallImIcons.greyInfoIcon = GreyInfoIcon;
CallImIcons.deleteBinIconDashed = DeleteBinIconDashed;
CallImIcons.commentIcon = CommentIcon;
CallImIcons.rejectIcon = RejectIcon;
CallImIcons.markRemindedIcon = MarkRemindedIcon;
CallImIcons.advanceNextIcon = AdvanceNextIcon;
CallImIcons.redoSectionIcon = RedoSectionIcon;
CallImIcons.notifyIcon = NotifyIcon;
CallImIcons.reconsiderIcon = ReconsiderIcon;
CallImIcons.reinstateIcon = ReinstateIcon;
CallImIcons.evaluateAnswerIcon = EvaluateAnswerIcon;
CallImIcons.keptInViewIcon = KeptInViewIcon;
CallImIcons.shortlistIcon = ShortlistIcon;
CallImIcons.collapseArrowRight = CollapseArrowRight;
CallImIcons.collapseArrowDown = CollapseArrowDown;
CallImIcons.ehrSyncIcon = EhrSyncIcon;
CallImIcons.exemptionRequestIcon = ExemptionRequestIcon;
CallImIcons.exemptionRevokeIcon = ExemptionRevokeIcon;

function ImIcons(props) {
  return CallImIcons[props.name](props);
}

export default ImIcons;
